import type { BloodResource, Donor, UrgentRequest, BloodBank, RequestHistoryItem, BloodCamp } from './types';

export const MOCK_RESOURCES: BloodResource[] = [
  { id: '1', bloodType: 'A+', quantity: 50, location: 'D Y Patil Hospital, Nerul', status: 'Available' },
  { id: '2', bloodType: 'O-', quantity: 10, location: 'D Y Patil Hospital, Nerul', status: 'Low' },
  { id: '3', bloodType: 'B+', quantity: 5, location: 'Terna Speciality Hospital, Nerul', status: 'Critical' },
  { id: '4', bloodType: 'AB+', quantity: 25, location: 'MGM Hospital, Vashi', status: 'Available' },
  { id: '5', bloodType: 'O+', quantity: 80, location: 'Red Cross Center', status: 'Available' },
  { id: '6', bloodType: 'A-', quantity: 15, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Low' },
  { id: '7', bloodType: 'B-', quantity: 3, location: 'D Y Patil Hospital, Nerul', status: 'Critical' },
  { id: '8', bloodType: 'AB-', quantity: 8, location: 'Red Cross Center', status: 'Low' },
  { id: '9', bloodType: 'A+', quantity: 40, location: 'Apollo Hospital, Navi Mumbai', status: 'Available' },
  { id: '10', bloodType: 'O+', quantity: 35, location: 'MGM Hospital, Vashi', status: 'Available' },
  { id: '11', bloodType: 'B+', quantity: 20, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Available' },
  { id: '12', bloodType: 'A+', quantity: 30, location: 'Reliance Hospital, Navi Mumbai', status: 'Available' },
  { id: '13', bloodType: 'B+', quantity: 30, location: 'MGM Hospital, Vashi', status: 'Available' },
  { id: '14', bloodType: 'A+', quantity: 30, location: 'Reliance Hospital, Navi Mumbai', status: 'Available' },
  { id: '15', bloodType: 'B-', quantity: 30, location: 'D Y Patil Hospital, Nerul', status: 'Available' },
];

export const MOCK_ACTIVE_REQUESTS: UrgentRequest[] = [
    {
        id: 'req1',
        bloodType: 'O-',
        quantity: 5,
        hospital: 'D Y Patil Hospital, Nerul',
        location: 'Nerul, Navi Mumbai',
        urgency: 'Critical',
        timePosted: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        status: 'Active',
    },
    {
        id: 'req2',
        bloodType: 'A+',
        quantity: 10,
        hospital: 'Terna Speciality Hospital, Nerul',
        location: 'Nerul, Navi Mumbai',
        urgency: 'High',
        timePosted: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        status: 'Active',
    },
    {
        id: 'req3',
        bloodType: 'B-',
        quantity: 3,
        hospital: 'Fortis Hiranandani Hospital, Vashi',
        location: 'Vashi, Navi Mumbai',
        urgency: 'Moderate',
        timePosted: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
        status: 'Active',
    }
];

export const MOCK_DONORS: Donor[] = [
  { id: 'd1', name: 'Aarav Sharma', bloodType: 'A+', location: 'Mumbai', lastDonation: '2024-05-15', contact: '9876543210' },
  { id: 'd2', name: 'Vivaan Singh', bloodType: 'O-', location: 'Delhi', lastDonation: '2024-04-20', contact: '9876543211' },
  { id: 'd3', name: 'Aditya Kumar', bloodType: 'B+', location: 'Bangalore', lastDonation: '2024-02-10', contact: '9876543212' },
  { id: 'd4', name: 'Vihaan Gupta', bloodType: 'AB+', location: 'Mumbai', lastDonation: '2024-06-01', contact: '9876543213' },
  { id: 'd5', name: 'Arjun Patel', bloodType: 'O+', location: 'Delhi', lastDonation: '2023-11-25', contact: '9876543214' },
  { id: 'd6', name: 'Sai Reddy', bloodType: 'A-', location: 'Hyderabad', lastDonation: '2024-01-05', contact: '9876543215' },
  { id: 'd7', name: 'Reyansh Mishra', bloodType: 'B-', location: 'Kolkata', lastDonation: '2024-03-22', contact: '9876543216' },
  { id: 'd8', name: 'Krishna Yadav', bloodType: 'AB-', location: 'Chennai', lastDonation: '2024-05-30', contact: '9876543217' },
  { id: 'd9', name: 'Ishaan Verma', bloodType: 'A+', location: 'Pune', lastDonation: '2024-02-18', contact: '9876543218' },
  { id: 'd10', name: 'Ayaan Khan', bloodType: 'O+', location: 'Ahmedabad', lastDonation: '2024-04-12', contact: '9876543219' },
  { id: 'd11', name: 'Ananya Sharma', bloodType: 'B+', location: 'Mumbai', lastDonation: '2024-05-01', contact: '9876543220' },
  { id: 'd12', name: 'Diya Singh', bloodType: 'A+', location: 'Delhi', lastDonation: '2024-03-10', contact: '9876543221' },
  { id: 'd13', name: 'Myra Kumar', bloodType: 'O-', location: 'Bangalore', lastDonation: '2024-06-05', contact: '9876543222' },
  { id: 'd14', name: 'Saanvi Gupta', bloodType: 'AB+', location: 'Kolkata', lastDonation: '2023-12-15', contact: '9876543223' },
  { id: 'd15', name: 'Aadhya Patel', bloodType: 'B-', location: 'Chennai', lastDonation: '2024-04-25', contact: '9876543224' },
  { id: 'd16', name: 'Kiara Reddy', bloodType: 'O+', location: 'Hyderabad', lastDonation: '2024-01-20', contact: '9876543225' },
  { id: 'd17', name: 'Priya Mishra', bloodType: 'A-', location: 'Pune', lastDonation: '2024-05-18', contact: '9876543226' },
  { id: 'd18', name: 'Riya Yadav', bloodType: 'AB-', location: 'Ahmedabad', lastDonation: '2024-02-28', contact: '9876543227' },
  { id: 'd19', name: 'Shanaya Verma', bloodType: 'B+', location: 'Mumbai', lastDonation: '2024-04-02', contact: '9876543228' },
  { id: 'd20', name: 'Zara Khan', bloodType: 'O-', location: 'Delhi', lastDonation: '2024-03-29', contact: '9876543229' },
];

export const MOCK_REQUEST_HISTORY: RequestHistoryItem[] = [
    {
        id: 'hist1',
        date: '2024-06-10',
        hospital: 'MGM Hospital, Vashi',
        bloodType: 'AB-',
        quantity: 2,
        status: 'Fulfilled',
        fulfilledBy: 'Jane Smith',
        location: 'Vashi, Navi Mumbai',
        urgency: 'High',
        timePosted: new Date('2024-06-10T10:00:00Z').toISOString(),
    },
    {
        id: 'hist2',
        date: '2024-05-28',
        hospital: 'D Y Patil Hospital, Nerul',
        bloodType: 'O-',
        quantity: 8,
        status: 'Fulfilled',
        fulfilledBy: 'Red Cross Center',
        location: 'Nerul, Navi Mumbai',
        urgency: 'Critical',
        timePosted: new Date('2024-05-28T14:30:00Z').toISOString(),
    },
    {
        id: 'hist3',
        date: '2024-06-05',
        hospital: 'Fortis Hiranandani Hospital, Vashi',
        bloodType: 'A+',
        quantity: 4,
        status: 'Expired',
        location: 'Vashi, Navi Mumbai',
        urgency: 'Moderate',
        timePosted: new Date('2024-06-05T08:00:00Z').toISOString(),
    },
];


export const MOCK_BLOOD_BANKS: BloodBank[] = [
    { id: 'bb1', name: 'Metro Blood Bank', location: 'Downtown' },
    { id: 'bb2', name: 'Uptown Donation Center', location: 'Uptown' },
    { id: 'bb3', name: 'Suburban Community Bank', location: 'Suburbia' },
    { id: 'bb4', name: 'Red Cross Central', location: 'City Center' },
];

export const MOCK_CAMPS: BloodCamp[] = [
  {
    id: 'camp1',
    name: 'Mega Blood Donation Drive',
    location: 'Inorbit Mall, Vashi, Navi Mumbai',
    date: '2024-08-15',
    organizer: 'Lions Club of Vashi',
    timings: '10:00 AM - 05:00 PM',
  },
  {
    id: 'camp2',
    name: 'Community Health & Blood Donation',
    location: 'Seawoods Grand Central, Seawoods, Navi Mumbai',
    date: '2024-08-20',
    organizer: 'Rotary Club of Navi Mumbai',
    timings: '11:00 AM - 06:00 PM',
  },
  {
    id: 'camp3',
    name: 'NSS Blood Donation Camp',
    location: 'D.Y. Patil University, Nerul, Navi Mumbai',
    date: '2024-09-01',
    organizer: 'NSS Unit, D.Y. Patil',
    timings: '09:00 AM - 04:00 PM',
  },
   {
    id: 'camp4',
    name: 'Annual Donation Camp',
    location: 'Urban Haat, CBD Belapur, Navi Mumbai',
    date: '2024-09-10',
    organizer: 'Navi Mumbai Municipal Corporation',
    timings: '10:00 AM - 05:00 PM',
  },
  {
    id: 'camp5',
    name: 'Life Savers Blood Camp',
    location: 'Wonders Park, Nerul, Navi Mumbai',
    date: '2024-09-22',
    organizer: 'Give Blood, Give Life Foundation',
    timings: '09:00 AM - 03:00 PM',
  },
  {
    id: 'camp6',
    name: 'Pre-Festive Season Donation Drive',
    location: 'Kharghar Valley Golf Course, Kharghar',
    date: '2024-10-05',
    organizer: 'Tata Memorial Hospital',
    timings: '11:00 AM - 04:00 PM',
  },
];
